spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost/shn
    username: shogun
#    password: set from command line --spring.datasource.password="pass"
    driverClassName: com.mysql.jdbc.Driver
    test-on-borrow: true
    test-while-idle: true
    validation-query: select 1;
    maxActive: 1
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: validate
        hbm2ddl:
          import_files: